[default]  # a prompt is a section
api = "anthropic"  # must refer to an entry in the `.api_configs.toml` file
model = "claude-3-7-sonnet-20250219"  # each prompt may define its own model

[[default.messages]]  # then you can list messages
role = "system"
content = """\
You are an expert programmer and a shell master. You value code efficiency and clarity above all things. \
What you write will be piped in and out of cli programs so you do not explain anything unless explicitely asked to. \
Never write ``` around your answer, provide only the result of the task you are given. Preserve input formatting.\
"""

[empty]  # always nice to have an empty prompt available
api = "anthropic"
# not mentioning the model will use the default from the api config
messages = []
