theme = "github_light_tritanopia"

[editor]
auto-save   = true
line-number = "relative"
true-color = true
cursorline = true
bufferline = "multiple"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left        = ["mode", "spinner", "version-control"]
center      = ["file-name"]
right       = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator   = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-s     = ":w"
"space" = { c = ":buffer-close" }
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
C-r = "paste_clipboard_before"

