theme               = "ayumirage_custom"

[editor]
auto-save               = true
auto-completion         = true
line-number             = "relative"
true-color              = true
cursorline              = false
bufferline              = "multiple"
gutters                 = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
popup-border            = "all"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "hint"
# Minimum severity to show a diagnostic on other lines:
other-lines = "info"
 
[editor.cursor-shape]
insert              = "bar"
normal              = "block"
select              = "underline"

[editor.file-picker]
hidden              = false

[editor.statusline]
left                = ["mode", "spinner", "version-control"]
center              = ["file-name"]
right               = ["diagnostics", "selections", "position", "file-type"]
separator           = "│"
mode.normal         = "NORMAL"
mode.insert         = "INSERT"
mode.select         = "SELECT"

[editor.lsp]
display-inlay-hints = false

[keys.normal]
space.c             = ":buffer-close"
"ret"               = "goto_word"

[keys.normal."'"]
_                   = "@ File Management\n"
t                   = "@:sh touch <C-r>%"
r                   = "@:sh rm <C-r>%"
e                   = "@:sh mkdir <C-r>%"
w                   = "@:sh mv <C-r>% <C-r>%"
c                   = "@:sh cp <C-r>% <C-r>%"

0                   = ":x"

[keys.insert]
j                   = { k             = "normal_mode" } # Maps `jk` to exit insert mode
C-r                 = "paste_clipboard_before"
