theme               = "base16_transparent"

[editor]
auto-save           = true
auto-completion     = true
line-number         = "relative"
true-color          = true
cursorline          = false
bufferline          = "multiple"
gutters             = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
popup-border        = "all"

[editor.cursor-shape]
insert              = "bar"
normal              = "block"
select              = "underline"

[editor.file-picker]
hidden              = false

[editor.statusline]
left                = ["mode", "spinner", "version-control"]
center              = ["file-name"]
right               = ["diagnostics", "selections", "position", "file-type"]
separator           = "│"
mode.normal         = "NORMAL"
mode.insert         = "INSERT"
mode.select         = "SELECT"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"space"             = { c     = ":buffer-close" }
y                   = "yank_main_selection_to_clipboard"
p                   = "paste_clipboard_before"
C-l                 = ":toggle-option lsp.display-inlay-hints"

[keys.insert]
j                   = { k             = "normal_mode" } # Maps `jk` to exit insert mode
C-r                 = "paste_clipboard_before"
