[[language]]
name = "python"
auto-format = true
roots = ["pyproject.toml", "pyrightconfig.json", "Poetry.lock"]
language-servers = [
    { name = "pyright" },
    { name = "ruff-lsp" },
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
lint = false
inlayHint.enable = true

[language-server.ruff-lsp]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = ["--line-length", "120", "--quiet", "-"]

[[language]]
name = "tfvars"
auto-format = true
formatter = { command = "terraform", args = ["fmt", "-"]}

[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true
