[[language]]
name = "python"
auto-format = true
roots = ["pyproject.toml", "pyrightconfig.json", "Poetry.lock"]
language-servers = [  "ruff", "pyright"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
except-features = ["format", "code-action"]

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
typeCheckingMode = "basic"
diagnosticMode = "openFilesOnly"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language.formatter]
command = "ruff"
args = ["format", "--line-length", "120", "--quiet", "-"]

[[language]]
name = "tfvars"
auto-format = true
formatter = { command = "terraform", args = ["fmt", "-"]}

[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[language-server]
biome = { command = "bun", args = ["run", "biome", "lsp-proxy"] }

[language-server.tailwindcss-ls]
command = "bun"
args = ["run", "tailwindcss-language-server", "--stdio"]

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "tailwindcss-ls" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "tailwindcss-ls" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "tailwindcss-ls" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "tailwindcss-ls" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "svelte"
auto-format = true
block-comment-tokens = {start = "<!--", end = "-->"}
language-servers = ["svelteserver", "tailwindcss-ls"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
